#!/bin/bash

# Check if the storage file exists
if [ ! -f storage ]; then
  echo "Storage file not found!"
  exit 1
fi

# Read the current number of tasks from the storage
current_tasks=$(cat storage)

# Increase the number of tasks by 8
new_tasks=$((current_tasks + 8))


# Check if the number of tasks reaches or exceeds 100
if [ $new_tasks -ge 100 ]; then
  echo "from producer: Now I will take a rest!"
  exit 0
fi

# Print the current total after increasing
echo "from producer: current total is $new_tasks"


# Update the storage file with the new number of tasks
echo $new_tasks > storage


# Call the consumer to continue
./consumer